---
driver:
  name: vagrant

provisioner:
  require_chef_omnibus: true
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    - recipe[cleanup]
    - recipe[test]
