inherit_from: .rubocop_todo.yml

# Offense count: 2
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 180

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false
